Repository yeolsimee/ROUMO-Server, pull requests merged in 2023-04, with the labels that each got.

#35 refactor(checkuser): isNewUser 값으로 새로운 유저인지 확인하는 값 추가
  src/main/java/com/yeolsimee/moneysaving/app/user/controller/LoginController.java
  src/main/java/com/yeolsimee/moneysaving/app/user/dto/LoginDto.java
  src/main/java/com/yeolsimee/moneysaving/filter/FirebaseTokenFilter.java
Labels: refactor

#37 루틴 수정하기
  src/main/java/com/yeolsimee/moneysaving/app/common/response/ResponseMessage.java
  src/main/java/com/yeolsimee/moneysaving/app/routine/controller/RoutineController.java
  src/main/java/com/yeolsimee/moneysaving/app/routine/dto/RoutineRequest.java
  src/main/java/com/yeolsimee/moneysaving/app/routine/entity/Routine.java
  src/main/java/com/yeolsimee/moneysaving/app/routine/service/RoutineService.java
  src/main/java/com/yeolsimee/moneysaving/app/routineday/dto/DayResponse.java
  src/main/java/com/yeolsimee/moneysaving/app/routineday/entity/RoutineDays.java
  src/main/java/com/yeolsimee/moneysaving/util/TimeUtils.java
  src/test/java/com/yeolsimee/moneysaving/acceptance/RoutineAcceptanceTest.java
  src/test/java/com/yeolsimee/moneysaving/acceptance/RoutineSteps.java
Labels: enhancement

#42 feature(userinfo) 사용자 추가정보 필터에 체크 추가 및 클래스 이름 변경
  src/main/java/com/yeolsimee/moneysaving/app/routine/service/RoutineService.java
  src/main/java/com/yeolsimee/moneysaving/app/user/controller/UserController.java
  src/main/java/com/yeolsimee/moneysaving/app/user/dto/UserInfoRequest.java
  src/main/java/com/yeolsimee/moneysaving/app/user/dto/UserInfoResponse.java
  src/main/java/com/yeolsimee/moneysaving/app/user/entity/User.java
  src/main/java/com/yeolsimee/moneysaving/app/user/service/UserService.java
  src/main/java/com/yeolsimee/moneysaving/app/user/validator/RegisterValidator.java
  src/main/java/com/yeolsimee/moneysaving/config/SecurityConfig.java
  src/main/java/com/yeolsimee/moneysaving/filter/FirebaseTokenFilter.java
Labels: feature, refactor

#48 bugfix(category): category 추가 요청 응답값 템플릿 적용
  src/main/java/com/yeolsimee/moneysaving/app/category/controller/CategoryController.java
Labels: bug
